import createClient from "openapi-fetch";
import type { FilterKeys, PathsWithMethod, RequiredKeysOf } from "openapi-typescript-helpers";

import { withLoading } from "../loading";
import type { paths } from "./schema";
import type { ApiError, RefreshEvent } from "./types";

// Typed fetch client derived from the backend's OpenAPI schema (see schema.ts, regenerated by
// `npm run gen:api`) - request AND response shapes for every endpoint come from here now,
// not hand-maintained interfaces. baseUrl is the current origin (always same-origin in the
// browser; being absolute rather than a bare `/` path also lets the client run under jsdom in
// the Vitest suite, where `new Request("/relative")` would throw).
const client = createClient<paths>({
  baseUrl: typeof location === "undefined" ? "http://localhost" : location.origin,
  // Resolve `fetch` off the global per call rather than letting openapi-fetch capture it at
  // construction time - keeps `vi.stubGlobal("fetch", ...)` working in the Vitest suite.
  // openapi-fetch hands us a fully-built Request, so no second arg is needed.
  fetch: (request: Request) => fetch(request),
});

type GetOp<Path extends PathsWithMethod<paths, "get">> = FilterKeys<paths[Path], "get">;
type PostOp<Path extends PathsWithMethod<paths, "post">> = FilterKeys<paths[Path], "post">;
type DeleteOp<Path extends PathsWithMethod<paths, "delete">> = FilterKeys<paths[Path], "delete">;

type SuccessBody<Op> = Op extends { responses: { 200: { content: { "application/json": infer Body } } } }
  ? Body
  : never;
type OpParams<Op> = Op extends { parameters: infer Params } ? Params : never;
// Non-optional `requestBody` in the pattern: ops without a body have `requestBody?: never` in
// the generated schema, which would otherwise infer `Body` as `unknown` and make `body`
// spuriously required.
type OpBody<Op> = Op extends { requestBody: { content: { "application/json": infer Body } } } ? Body : never;

// Thin wrappers over openapi-fetch's `{ data, error, response }` result, preserving the
// throw-based ergonomics call sites across layers.ts/main.ts/plan.ts/refresh.ts/views.ts already
// use (see `ApiError`) - openapi-fetch itself never throws on a non-2xx response, it returns
// `error`.
//
// `error` alone isn't a reliable non-2xx signal, though: openapi-fetch only populates it by
// parsing the response body, so a non-ok response with an empty body (a bodyless 502/504 from a
// proxy, a 204, etc.) comes back with `error` undefined or an empty string. Checking
// `response.ok` directly catches that, and the `|| httpError(response)` fallback (not `??` -
// an empty-string `error` is falsy but useless) supplies a synthetic `ApiError` from the
// status line when there's no parsed body to surface.

function httpError(response: Response): ApiError {
  return { detail: response.statusText || `HTTP ${response.status}` };
}

export async function getJson<Path extends PathsWithMethod<paths, "get">>(
  path: Path,
  ...params: RequiredKeysOf<OpParams<GetOp<Path>>> extends never
    ? [OpParams<GetOp<Path>>?]
    : [OpParams<GetOp<Path>>]
): Promise<SuccessBody<GetOp<Path>>> {
  const { data, error, response } = await withLoading(() =>
    client.GET(path, (params[0] ? { params: params[0] } : undefined) as never),
  );
  if (!response.ok) throw (error as ApiError | undefined) || httpError(response);
  return data as SuccessBody<GetOp<Path>>;
}

// POST and DELETE take a single `init` object passed through to openapi-fetch: `body` for the
// routes with a request body (`/api/location`), `params` for the ones that key off a path
// segment or query string (`/api/genera/{taxon_id}`, `/api/refresh?target=`). Each half is
// required or optional exactly as the schema says (`body` required iff the op has one;
// `params` required iff it has a required path/query), and the `init` arg itself drops to
// optional only when neither half is required (`deleteJson("/api/refresh")`).
type BodyPart<Op> = OpBody<Op> extends never ? { body?: never } : { body: OpBody<Op> };
type ParamsPart<Op> =
  RequiredKeysOf<OpParams<Op>> extends never ? { params?: OpParams<Op> } : { params: OpParams<Op> };
type PostInit<Path extends PathsWithMethod<paths, "post">> = BodyPart<PostOp<Path>> &
  ParamsPart<PostOp<Path>>;
type DeleteInit<Path extends PathsWithMethod<paths, "delete">> = ParamsPart<DeleteOp<Path>>;

export async function postJson<Path extends PathsWithMethod<paths, "post">>(
  path: Path,
  ...init: RequiredKeysOf<PostInit<Path>> extends never ? [init?: PostInit<Path>] : [init: PostInit<Path>]
): Promise<SuccessBody<PostOp<Path>>> {
  const { data, error, response } = await withLoading(() =>
    client.POST(path, (init[0] ?? undefined) as never),
  );
  if (!response.ok) throw (error as ApiError | undefined) || httpError(response);
  return data as SuccessBody<PostOp<Path>>;
}

export async function deleteJson<Path extends PathsWithMethod<paths, "delete">>(
  path: Path,
  ...init: RequiredKeysOf<DeleteInit<Path>> extends never
    ? [init?: DeleteInit<Path>]
    : [init: DeleteInit<Path>]
): Promise<SuccessBody<DeleteOp<Path>>> {
  const { data, error, response } = await withLoading(() =>
    client.DELETE(path, (init[0] ?? undefined) as never),
  );
  if (!response.ok) throw (error as ApiError | undefined) || httpError(response);
  return data as SuccessBody<DeleteOp<Path>>;
}

/** Open the refresh progress stream (`GET /api/refresh/stream`). The endpoint is in the schema
 * as `text/event-stream`, but the per-message JSON shape isn't - `RefreshEvent` mirrors what
 * `foray.api.refresh_runner.broadcast` sends. `onEvent` gets each parsed update; a message
 * that isn't JSON goes to `onMalformed` instead. The caller owns `close()` and `onerror`. */
export function openRefreshStream(
  onEvent: (event: RefreshEvent) => void,
  onMalformed: (raw: string, error: unknown) => void,
): EventSource {
  const source = new EventSource("/api/refresh/stream");
  source.addEventListener("message", (message: MessageEvent<string>) => {
    let event: RefreshEvent;
    try {
      event = JSON.parse(message.data) as RefreshEvent;
    } catch (error) {
      onMalformed(message.data, error);
      return;
    }
    onEvent(event);
  });
  return source;
}
