import createClient from "openapi-fetch";
import type { FilterKeys, PathsWithMethod, RequiredKeysOf } from "openapi-typescript-helpers";

import type { paths } from "./schema";
import type { ApiError } from "./types";

// Typed fetch client derived from the backend's OpenAPI schema (see schema.ts, regenerated by
// `npm run gen:api`) - request AND response shapes for every endpoint come from here now,
// not hand-maintained interfaces.
const client = createClient<paths>({ baseUrl: "" });

type GetOp<Path extends PathsWithMethod<paths, "get">> = FilterKeys<paths[Path], "get">;
type PostOp<Path extends PathsWithMethod<paths, "post">> = FilterKeys<paths[Path], "post">;

type SuccessBody<Op> = Op extends { responses: { 200: { content: { "application/json": infer Body } } } }
  ? Body
  : never;
type OpParams<Op> = Op extends { parameters: infer Params } ? Params : never;
type OpBody<Op> = Op extends { requestBody?: { content: { "application/json": infer Body } } } ? Body : never;

// Thin wrappers over openapi-fetch's `{ data, error, response }` result, preserving the
// throw-based ergonomics call sites across layers.ts/main.ts/plan.ts/refresh.ts/views.ts already
// use (see `ApiError`) - openapi-fetch itself never throws on a non-2xx response, it returns
// `error`.
//
// `error` alone isn't a reliable non-2xx signal, though: openapi-fetch only populates it by
// parsing the response body, so a non-ok response with an empty body (a bodyless 502/504 from a
// proxy, a 204, etc.) comes back as `{ data: undefined, error: undefined }` - falsy `error`, but
// `data` isn't actually there either. Checking `response.ok` directly catches that case too,
// with a synthetic `ApiError` when there was no parsed body to surface.

function httpError(response: Response): ApiError {
  return { detail: response.statusText || `HTTP ${response.status}` };
}

export async function getJson<Path extends PathsWithMethod<paths, "get">>(
  path: Path,
  ...params: RequiredKeysOf<OpParams<GetOp<Path>>> extends never ? [OpParams<GetOp<Path>>?] : [OpParams<GetOp<Path>>]
): Promise<SuccessBody<GetOp<Path>>> {
  const { data, error, response } = await client.GET(
    path,
    (params[0] ? { params: params[0] } : undefined) as never,
  );
  if (!response.ok) throw (error as ApiError | undefined) ?? httpError(response);
  return data as SuccessBody<GetOp<Path>>;
}

export async function postJson<Path extends PathsWithMethod<paths, "post">>(
  path: Path,
  body: OpBody<PostOp<Path>>,
): Promise<SuccessBody<PostOp<Path>>> {
  const { data, error, response } = await client.POST(path, { body } as never);
  if (!response.ok) throw (error as ApiError | undefined) ?? httpError(response);
  return data as SuccessBody<PostOp<Path>>;
}
