/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/genera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Genera
         * @description Genus catalog search (issue #79) - empty query returns the most-observed genera.
         */
        get: operations["get_genera_api_genera_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/genera/selected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Selected Genera
         * @description This device's selected genera (issue #79 Phase 2) - empty means "everything nearby".
         */
        get: operations["get_selected_genera_api_genera_selected_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/genera/{taxon_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Selected Genus */
        post: operations["add_selected_genus_api_genera__taxon_id__post"];
        /** Remove Selected Genus */
        delete: operations["remove_selected_genus_api_genera__taxon_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Coverage
         * @description Coverage regions with their latest ingest timestamps.
         */
        get: operations["get_coverage_api_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Destinations */
        get: operations["destinations_api_destinations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_api_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observation Photos */
        get: operations["observation_photos_api_observations_photos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alerts */
        get: operations["get_alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations/precise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Observations Precise
         * @description Precise observations near an explicit lat/lng (a focused destination), falling back to
         *     home + its search radius when omitted - same `lat`/`lng`/`radius_km` override pattern as
         *     `/api/camps` and `/api/trails`.
         */
        get: operations["observations_precise_api_observations_precise_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/camps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Camps
         * @description Campsites near a region (by id) or an explicit lat/lng, free-first by distance.
         */
        get: operations["get_camps_api_camps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/land": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Land
         * @description Public-land ownership polygons near a region (by id) or an explicit lat/lng.
         */
        get: operations["get_land_api_land_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trails
         * @description Trails near a region (by id) or an explicit lat/lng, nearest to the hotspot first.
         *
         *     ``kind``/``limit`` scope this to e.g. just the nearest 20 trailheads for a destination
         *     card's Trails tab, instead of every path/route/trailhead in the radius.
         */
        get: operations["get_trails_api_trails_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trails/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trail Network
         * @description The real trail for a selected trailhead - live OSM topology when available, otherwise
         *     the nearest cached path/route (see ``trails.resolve_trail_network``). ``trail_id`` is a
         *     query param, not a path segment - trail ids embed a literal ``/`` (``osm:node/123``).
         */
        get: operations["get_trail_network_api_trails_network_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan
         * @description Corridor trip plan: fruiting stops (with nearby camp + trail) from start to destination.
         *
         *     ``destination`` is auto-picked (best-scoring region reachable from ``start``) when omitted.
         */
        get: operations["plan_api_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Location */
        post: operations["set_location_api_location_post"];
        /**
         * Delete Location
         * @description Issue #81: let a visitor delete their saved home/radius override. Scoped to the
         *     caller's own device_id cookie - never touches another visitor's row.
         */
        delete: operations["delete_location_api_location_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_refresh_post"];
        /** Cancel Refresh */
        delete: operations["cancel_refresh_api_refresh_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Refresh Stream */
        get: operations["refresh_stream_api_refresh_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertHit */
        AlertHit: {
            /** Taxon Id */
            taxon_id: number;
            /** Name */
            name: string;
            /** Common Name */
            common_name: string | null;
            /** Count */
            count: number;
            /** Last Seen */
            last_seen: string;
            /** Place Guess */
            place_guess: string | null;
            /** Uri */
            uri: string | null;
            /** Obscured */
            obscured: boolean;
        };
        /** AlertRegion */
        AlertRegion: {
            /** Region Id */
            region_id: string;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Distance Km */
            distance_km: number;
            /** Total */
            total: number;
            /** Species */
            species: components["schemas"]["AlertHit"][];
        };
        /** CalendarBucket */
        CalendarBucket: {
            /** Total */
            total: number;
            /** Species */
            species: {
                [key: string]: number;
            };
        };
        /** CampSite */
        CampSite: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Fee */
            fee: string | null;
            /** Free */
            free: boolean | null;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Distance Km */
            distance_km: number;
            /** Source */
            source: string;
            /** Url */
            url: string;
        };
        /** ConfigResponse */
        ConfigResponse: {
            home: components["schemas"]["Home"];
            /** Cell Deg */
            cell_deg: number;
            /** Recent Weeks */
            recent_weeks: number;
            /** Refreshing */
            refreshing: boolean;
            /** Last Error */
            last_error: string | null;
        };
        /** CoverageRegionResponse */
        CoverageRegionResponse: {
            /** Name */
            name: string;
            /** Place Id */
            place_id: number;
            /** Last Ingest */
            last_ingest: string | null;
            /** Observations Ingested */
            observations_ingested: number;
        };
        /**
         * GenusResult
         * @description A genus catalog search hit (issue #79).
         *
         *     ``common_name`` is optional - most of the ~6,018 Fungi genera lack an English common name
         *     on iNat, so ``name`` (scientific) is the primary label, not a fallback.
         */
        GenusResult: {
            /** Taxon Id */
            taxon_id: number;
            /** Name */
            name: string;
            /** Common Name */
            common_name: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Home */
        Home: {
            /**
             * Name
             * @default Home
             */
            name: string;
            /**
             * Lat
             * @default 47.6062
             */
            lat: number;
            /**
             * Lng
             * @default -122.3321
             */
            lng: number;
            /**
             * Radius Km
             * @default 150
             */
            radius_km: number;
        };
        /** LandUnit */
        LandUnit: {
            /** Id */
            id: string;
            /** Agency */
            agency: string;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
        };
        /** LocationBody */
        LocationBody: {
            /** Query */
            query?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /** Name */
            name?: string | null;
            /** Radius Km */
            radius_km?: number | null;
        };
        /** LocationResponse */
        LocationResponse: {
            home: components["schemas"]["Home"];
        };
        /** ObservationPhoto */
        ObservationPhoto: {
            /** Url */
            url: string;
            /** License Code */
            license_code: string;
            /** Attribution */
            attribution: string;
        };
        /** PreciseObservation */
        PreciseObservation: {
            /** Id */
            id: number;
            /** Taxon Id */
            taxon_id: number;
            /** Name */
            name: string;
            /** Common Name */
            common_name: string | null;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Observed On */
            observed_on: string | null;
            /** Uri */
            uri: string | null;
        };
        /** RecentObservation */
        RecentObservation: {
            /** Id */
            id: number;
            /** Taxon Id */
            taxon_id: number;
            /** Name */
            name: string;
            /** Common Name */
            common_name: string | null;
            /** Observed On */
            observed_on: string | null;
            /** Place Guess */
            place_guess: string | null;
            /** Uri */
            uri: string | null;
            /** Obscured */
            obscured: boolean;
            /** Photos */
            photos: components["schemas"]["ObservationPhoto"][];
        };
        /** RecentObservationsPage */
        RecentObservationsPage: {
            /** Observations */
            observations: components["schemas"]["RecentObservation"][];
            /** Has More */
            has_more: boolean;
        };
        /** RegionScore */
        RegionScore: {
            /** Region Id */
            region_id: string;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Distance Km */
            distance_km: number;
            /** Score */
            score: number;
            /** Score Norm */
            score_norm: number;
            /** N Species */
            n_species: number;
            /** Recent Count */
            recent_count: number;
            /** Species */
            species: components["schemas"]["SpeciesHit"][];
        };
        /**
         * SpeciesHit
         * @description A target-genus contribution to a ranked region.
         *
         *     ``name`` (scientific) is the primary display label; ``common_name`` is optional
         *     secondary enrichment - most of the ~6,018-genus catalog lacks an English common name.
         */
        SpeciesHit: {
            /** Taxon Id */
            taxon_id: number;
            /** Name */
            name: string;
            /** Common Name */
            common_name: string | null;
            /** Month Count */
            month_count: number;
            /** Total Count */
            total_count: number;
            /** W Pheno */
            w_pheno: number;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Status */
            status: string;
        };
        /** Stop */
        Stop: {
            /** Order */
            order: number;
            /** Region Id */
            region_id: string;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Score Norm */
            score_norm: number;
            /** N Species */
            n_species: number;
            /** Recent Count */
            recent_count: number;
            /** Species */
            species: components["schemas"]["SpeciesHit"][];
            /** Progress Km */
            progress_km: number;
            /** Drive Km From Prev */
            drive_km_from_prev: number;
            /** Cumulative Drive Km */
            cumulative_drive_km: number;
            camp: components["schemas"]["CampSite"] | null;
            /** Camp Is Free */
            camp_is_free: boolean;
            trail: components["schemas"]["Trail"] | null;
            /** Trail Distance Km */
            trail_distance_km: number | null;
        };
        /** Trail */
        Trail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Distance Km */
            distance_km: number;
            /** Camp Distance Km */
            camp_distance_km: number | null;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
        };
        /** TrailPath */
        TrailPath: {
            trail: components["schemas"]["Trail"];
            /** Authoritative */
            authoritative: boolean;
        };
        /** TripPlan */
        TripPlan: {
            /** Start Lat */
            start_lat: number;
            /** Start Lng */
            start_lng: number;
            /** Destination Lat */
            destination_lat: number;
            /** Destination Lng */
            destination_lng: number;
            /** Destination Name */
            destination_name: string | null;
            /** Auto Destination */
            auto_destination: boolean;
            /** Corridor Km */
            corridor_km: number;
            /** Months */
            months: number[];
            /** N Stops */
            n_stops: number;
            /** Total Drive Km */
            total_drive_km: number;
            /** Stops */
            stops: components["schemas"]["Stop"][];
            /** Skipped Unreachable */
            skipped_unreachable: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    get_genera_api_genera_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenusResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_selected_genera_api_genera_selected_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenusResult"][];
                };
            };
        };
    };
    add_selected_genus_api_genera__taxon_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_selected_genus_api_genera__taxon_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coverage_api_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageRegionResponse"][];
                };
            };
        };
    };
    destinations_api_destinations_get: {
        parameters: {
            query?: {
                months?: string | null;
                species?: string;
                radius_km?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionScore"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calendar_api_calendar_get: {
        parameters: {
            query: {
                region_id: string;
                species?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["CalendarBucket"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observation_photos_api_observations_photos_get: {
        parameters: {
            query: {
                region_id: string;
                species?: string;
                months?: string | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentObservationsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alerts_api_alerts_get: {
        parameters: {
            query?: {
                species?: string;
                weeks?: number | null;
                radius_km?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRegion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observations_precise_api_observations_precise_get: {
        parameters: {
            query?: {
                species?: string;
                months?: string | null;
                lat?: number | null;
                lng?: number | null;
                radius_km?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreciseObservation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camps_api_camps_get: {
        parameters: {
            query?: {
                region_id?: string | null;
                lat?: number | null;
                lng?: number | null;
                radius_km?: number;
                free_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampSite"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_land_api_land_get: {
        parameters: {
            query?: {
                region_id?: string | null;
                lat?: number | null;
                lng?: number | null;
                radius_km?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandUnit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trails_api_trails_get: {
        parameters: {
            query?: {
                region_id?: string | null;
                lat?: number | null;
                lng?: number | null;
                radius_km?: number;
                kind?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trail_network_api_trails_network_get: {
        parameters: {
            query: {
                trail_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrailPath"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_plan_get: {
        parameters: {
            query?: {
                months?: string | null;
                species?: string;
                start?: string | null;
                destination?: string | null;
                corridor_km?: number;
                max_stops?: number;
                max_drive_km?: number;
                camp_radius_km?: number;
                require_free_camp?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_location_api_location_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_location_api_location_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    refresh_api_refresh_post: {
        parameters: {
            query?: {
                target?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_refresh_api_refresh_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    refresh_stream_api_refresh_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent progress events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
