/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Per-visitor home plus the server's map, tile and refresh-state settings (see ``ConfigResponse``).
         */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/genera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Genera
         * @description Genus catalog search (issue #79) - empty query returns the most-observed genera.
         */
        get: operations["get_genera_api_genera_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/genera/selected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Selected Genera
         * @description This device's selected genera (issue #79 Phase 2) - empty means "everything nearby".
         */
        get: operations["get_selected_genera_api_genera_selected_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/genera/{taxon_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Selected Genus
         * @description Add a genus to this device's target list (idempotent).
         */
        post: operations["add_selected_genus_api_genera__taxon_id__post"];
        /**
         * Remove Selected Genus
         * @description Remove a genus from this device's target list (idempotent).
         */
        delete: operations["remove_selected_genus_api_genera__taxon_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Coverage
         * @description Coverage regions with their latest ingest timestamps.
         */
        get: operations["get_coverage_api_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness only - the process can answer a request. No DB dependency on purpose: a
         *     Postgres blip should surface via `/healthz/data` going stale, not take the whole
         *     container out of rotation.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz Data
         * @description Freshness: any layer whose latest success is older than
         *     ``interval_hours * observability.data_freshness_multiplier`` (default 2x) fails the check
         *     - a non-200 response a cron/alerting layer or an uptime monitor can page on.
         */
        get: operations["healthz_data_healthz_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz Backlog
         * @description Backfill-queue depth + recent drain rate per kind (issue #334 PR 3) - never a failing
         *     check (no 503 here), just the numbers behind "is this catching up".
         */
        get: operations["healthz_backlog_healthz_backlog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Prometheus text-exposition scrape target (issue #338 PR 1) - see this module's
         *     docstring for scope. A fresh `CollectorRegistry` per request rather than one shared
         *     process-wide registry: `ForayCollector.collect()` already does all its work against
         *     Postgres on every call, so there's no in-process state a shared registry would actually
         *     be caching, and a fresh one sidesteps `prometheus_client`'s duplicate-registration error
         *     on module reload (e.g. multiple `TestClient` apps in the same test process). Not gated by
         *     any auth - matches `/healthz`/`/healthz/data`'s existing unauthenticated precedent;
         *     restricting scrape access (private network, firewall rule) is an ops decision for #338 PR
         *     2's Prometheus deployment, not this endpoint's job.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Destinations
         * @description Ranked destinations around the visitor's home for the chosen months and genera (see
         *     ``scoring.rank_destinations``).
         */
        get: operations["destinations_api_destinations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calendar
         * @description The 12-month calendar for one region: total and per-genus record counts by month.
         */
        get: operations["calendar_api_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Observation Photos
         * @description A page of a region's recent research-grade observations with their displayable Creative Commons photos, newest
         *     first.
         */
        get: operations["observation_photos_api_observations_photos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alerts
         * @description The "Active now" list: regions with observations of the selected genera in the trailing ``weeks``.
         */
        get: operations["get_alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations/precise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Observations Precise
         * @description Precise observations near an explicit lat/lng (a focused destination), falling back to
         *     home + its search radius when omitted - same `lat`/`lng`/`radius_km` override pattern as
         *     `/api/camps` and `/api/trails`. `weeks` replaces the month filter with the trailing window
         *     `/api/alerts` uses, for the "active now" sort (issue #312).
         */
        get: operations["observations_precise_api_observations_precise_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations/{obs_id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Observation Thumbnail
         * @description One CC-licensed photo for a precise observation's map popup (issue #449), or null when iNat
         *     has none we may display. Fetched from iNat the first time a popup asks and cached in
         *     `observation_thumbnails` (the "none" answer too), so hovering across pins costs iNat at most
         *     one call per observation. Only serves observations already cached as precise, so this can't
         *     be used to proxy arbitrary iNat lookups.
         */
        get: operations["observation_thumbnail_api_observations__obs_id__thumbnail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations/thumbnails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Observation Thumbnails
         * @description Warm and return popup photos for many precise observations at once (issue #449), so a
         *     destination's pins already have theirs when one is hovered. Same rules as the per-pin
         *     endpoint - only cached precise observations, fetched from iNat once and cached (the "none"
         *     answer too) - but the missing ones are looked up together, ~200 per iNat request instead of
         *     one each. An iNat failure just leaves the missing ids out of the result (the client falls
         *     back to the per-pin endpoint), it doesn't fail the batch.
         */
        post: operations["observation_thumbnails_api_observations_thumbnails_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/camps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Camps
         * @description Campsites near a region (by id) or an explicit lat/lng, free-first by distance.
         *
         *     ``limit`` caps the ranked result, e.g. a destination card's Campgrounds tab.
         */
        get: operations["get_camps_api_camps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/destinations/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Region Places
         * @description Batch companion to ``/api/destinations/{region_id}/place`` (issue #301 F7): one request
         *     for a whole result page's card titles instead of ~one per card. Returns only the regions
         *     whose place name is already cached - the common case, since a grid cell's centroid never
         *     moves. Uncached regions are omitted; the caller falls back to the per-region endpoint
         *     (which does the throttled Nominatim round-trip) for whatever is left, so a cold cache is
         *     no slower than before and a warm one collapses ~75 requests into 1.
         */
        get: operations["get_region_places_api_destinations_places_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/destinations/{region_id}/place": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Region Place
         * @description The one notable place name for a destination card's title (issue #206) - a national
         *     forest, city, etc, whichever `geocode.notable_place_name` finds first for the region's
         *     centroid. Cached forever per region (`region_places`) since a grid cell's centroid
         *     never moves: the first card to render for a given region pays one Nominatim round-trip
         *     (throttled - see `geocode._throttle`), every later view of that region is a DB hit.
         *     A successful lookup that finds nothing notable nearby caches `None` too, so a remote
         *     region doesn't retry every time its card renders - a transient network/HTTP failure is
         *     NOT cached, so it gets retried on the next render instead of being stuck permanently
         *     titleless.
         */
        get: operations["get_region_place_api_destinations__region_id__place_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/destinations/{region_id}/satellite/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Region Satellite Image
         * @description A selected destination's aerial photo (#293 follow-up) - see `_region_satellite_bytes`.
         */
        get: operations["get_region_satellite_image_api_destinations__region_id__satellite_image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/destinations/{region_id}/satellite/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Region Satellite Labels
         * @description The same destination's transparent roads/place-labels overlay - see `_region_satellite_bytes`.
         */
        get: operations["get_region_satellite_labels_api_destinations__region_id__satellite_labels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/land": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Land
         * @description Pinnable public-land parcels near a point, nearest first (issue #311) - the Details
         *     view's "Public land" tab. Ownership only, no geometry (the map draws parcels from tiles).
         */
        get: operations["get_land_api_land_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trails
         * @description Trails near a region (by id) or an explicit lat/lng.
         *
         *     ``kind``/``limit`` scope this to e.g. just the nearest 20 trailheads for a destination
         *     card's Trails tab, instead of every path/route/trailhead in the radius. ``sort`` is
         *     ``nearest`` (default), ``relevance`` (named-route / longer trail / target-genus finds along
         *     the line first), or ``longest``; ``significant_only`` drops the unnamed OSM connector stubs.
         *     ``distinct_names=false`` skips the one-row-per-name collapse (the map layer wants every point).
         *     ``species`` scopes the relevance obs-density term to the device's selected genera.
         *
         *     Geometry is omitted (``with_geometry=False``): this feeds a name + distance row list, and
         *     selecting a row draws the real trail by fetching ``/api/trails/network`` for that one id.
         *     Returning every trail's full LineString here was megabytes of payload nothing rendered.
         */
        get: operations["get_trails_api_trails_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trails/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trail Network
         * @description The real trail for a selected trailhead - live OSM topology when available, otherwise
         *     the nearest cached path/route (see ``trails.resolve_trail_network``). ``trail_id`` is a
         *     query param, not a path segment - trail ids embed a literal ``/`` (``osm:node/123``).
         */
        get: operations["get_trail_network_api_trails_network_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles/satellite/{z}/{x}/{y}.jpg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Satellite Tile
         * @description One Esri World Imagery tile, proxied same-origin so the satellite basemap toggle (issue
         *     #340) stays under the existing CSP (`security.py`'s satellite fill is `'self'`-only).
         */
        get: operations["get_satellite_tile_api_tiles_satellite__z___x___y__jpg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles/trails/{z}/{x}/{y}.pbf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trails Tile
         * @description One trails vector tile (issue #336 PR 1) - see `_martin_tile`.
         */
        get: operations["get_trails_tile_api_tiles_trails__z___x___y__pbf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles/land/{z}/{x}/{y}.pbf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Land Tile
         * @description One public-land ownership vector tile (issue #336 PR 2) - see `_martin_tile`.
         */
        get: operations["get_land_tile_api_tiles_land__z___x___y__pbf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles/fire/{z}/{x}/{y}.pbf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fire Tile
         * @description One wildfire/burn-scar vector tile (issue #336 PR 2) - see `_martin_tile`.
         */
        get: operations["get_fire_tile_api_tiles_fire__z___x___y__pbf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan
         * @description Corridor trip plan: fruiting stops (with nearby camp + trail) from start to destination.
         *
         *     ``destination`` is auto-picked (best-scoring region reachable from ``start``) when omitted.
         *     ``waypoints``, when given, are the whole itinerary. Each ``pin`` is
         *     ``{region_id}:{camp|trail|land}:{feature_id}`` - a campground, trail or public-land parcel
         *     the user picked as that waypoint's exact stop point (issue #311; a parcel resolves to its
         *     entrance); a pin whose feature is no longer cached falls back
         *     to the region centroid.
         */
        get: operations["plan_api_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Location
         * @description Save this device's home and radius from a place name or coordinates. Never triggers an ingest.
         */
        post: operations["set_location_api_location_post"];
        /**
         * Delete Location
         * @description Issue #81: let a visitor delete their saved home/radius override. Scoped to the
         *     caller's own device_id cookie - never touches another visitor's row.
         */
        delete: operations["delete_location_api_location_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/location/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Location
         * @description Typeahead place search (issue #145): proxies Nominatim server-side so the browser never
         *     calls it directly and the one User-Agent/rate-limit policy (geocode._throttle) covers it.
         *     Degrades to an empty list on a geocoder failure - the autocomplete just shows no matches
         *     rather than surfacing an error mid-keystroke.
         */
        get: operations["search_location_api_location_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Start a background refresh of ``target`` around the visitor's home (one at a time, rate limited by IP).
         */
        post: operations["refresh_api_refresh_post"];
        /**
         * Cancel Refresh
         * @description Ask the running refresh to stop at its next checkpoint and close its HTTP client.
         */
        delete: operations["cancel_refresh_api_refresh_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Refresh Stream
         * @description Stream refresh progress as server-sent events until the refresh reports ``done`` or an ``error``.
         */
        get: operations["refresh_stream_api_refresh_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index
         * @description Serve the built single-page client (``index.html``), or a short hint if the bundle has not been built.
         */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertHit
         * @description One genus's recent sightings within an "Active now" region: count, latest date and the newest observation's
         *     link.
         */
        AlertHit: {
            /** Taxon Id */
            taxon_id: number;
            /** Name */
            name: string;
            /** Common Name */
            common_name: string | null;
            /**
             * Icon
             * @default generic
             * @enum {string}
             */
            icon: "gilled" | "bolete" | "bracket" | "crust" | "coral" | "puffball" | "earthstar" | "cup" | "morel" | "tooth" | "vase" | "jelly" | "stinkhorn" | "leafy-lichen" | "shrubby-lichen" | "rust" | "generic" | "trametes" | "amanita" | "laetiporus" | "pleurotus" | "fomitopsis" | "cerioporus" | "ganoderma" | "lactarius" | "stereum" | "schizophyllum" | "mycena" | "suillus" | "cladonia" | "omphalotus" | "coprinus" | "flavoparmelia" | "cantharellus" | "hericium" | "desarmillaria" | "lobaria" | "hypomyces" | "chlorophyllum" | "russula" | "cortinarius" | "artomyces" | "apioperdon" | "entoloma" | "agaricus" | "leucocoprinus" | "morchella";
            /** Count */
            count: number;
            /** Last Seen */
            last_seen: string;
            /** Place Guess */
            place_guess: string | null;
            /** Uri */
            uri: string | null;
            /** Obscured */
            obscured: boolean;
        };
        /**
         * AlertRegion
         * @description A region with recent sightings (``GET /api/alerts``), with its recent rain and nearby fire.
         */
        AlertRegion: {
            /** Region Id */
            region_id: string;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Distance Km */
            distance_km: number;
            /** Total */
            total: number;
            /** Species */
            species: components["schemas"]["AlertHit"][];
            /** Precip Recent 7D Mm */
            precip_recent_7d_mm?: number | null;
            /** Precip Recent 14D Mm */
            precip_recent_14d_mm?: number | null;
            /** Precip Recent 30D Mm */
            precip_recent_30d_mm?: number | null;
            /**
             * Fire Nearby
             * @default []
             */
            fire_nearby: components["schemas"]["FireNear"][];
        };
        /**
         * BacklogResponse
         * @description One backfill kind's queue depth + drain rate, as reported by ``/healthz/backlog``
         *     (issue #334 PR 3) - "is this catching up" answerable without a database console.
         */
        BacklogResponse: {
            /** Kind */
            kind: string;
            /** Backlog */
            backlog: number;
            /** Drain Rate Per Hour */
            drain_rate_per_hour: number | null;
            /** Job */
            job: string;
        };
        /**
         * CalendarBucket
         * @description One month of a region's calendar: the total record count and the count per genus label.
         */
        CalendarBucket: {
            /** Total */
            total: number;
            /** Species */
            species: {
                [key: string]: number;
            };
            /**
             * Icons
             * @default {}
             */
            icons: {
                [key: string]: "gilled" | "bolete" | "bracket" | "crust" | "coral" | "puffball" | "earthstar" | "cup" | "morel" | "tooth" | "vase" | "jelly" | "stinkhorn" | "leafy-lichen" | "shrubby-lichen" | "rust" | "generic" | "trametes" | "amanita" | "laetiporus" | "pleurotus" | "fomitopsis" | "cerioporus" | "ganoderma" | "lactarius" | "stereum" | "schizophyllum" | "mycena" | "suillus" | "cladonia" | "omphalotus" | "coprinus" | "flavoparmelia" | "cantharellus" | "hericium" | "desarmillaria" | "lobaria" | "hypomyces" | "chlorophyllum" | "russula" | "cortinarius" | "artomyces" | "apioperdon" | "entoloma" | "agaricus" | "leucocoprinus" | "morchella";
            };
        };
        /**
         * CampSite
         * @description A campground or reported campsite near a point. ``free`` is true only on an explicit no-fee signal, never
         *     guessed.
         */
        CampSite: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Fee */
            fee: string | null;
            /** Free */
            free: boolean | null;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Distance Km */
            distance_km: number;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /** Reservable */
            reservable?: boolean | null;
            /** Fee Low */
            fee_low?: number | null;
            /** Fee High */
            fee_high?: number | null;
            /** Camp Type */
            camp_type?: ("tent" | "rv" | "mixed" | "backcountry" | "group" | "equestrian" | "cabin" | "pitch") | null;
            /**
             * Pitch Count
             * @default 0
             */
            pitch_count: number;
        };
        /**
         * ConfigResponse
         * @description ``GET /api/config``: the visitor's home plus server-side map and tile settings.
         */
        ConfigResponse: {
            home: components["schemas"]["Home"];
            /** Region Radius Km */
            region_radius_km: number;
            /** Recent Weeks */
            recent_weeks: number;
            /** Refreshing */
            refreshing: boolean;
            /**
             * Rebuilding Phenology
             * @default false
             */
            rebuilding_phenology: boolean;
            /** Last Error */
            last_error: string | null;
            /**
             * Basemap Url
             * @default
             */
            basemap_url: string;
            /**
             * Terrain Url
             * @default
             */
            terrain_url: string;
            /**
             * Satellite Tiles Url
             * @default
             */
            satellite_tiles_url: string;
            /**
             * Trails Tiles Url
             * @default
             */
            trails_tiles_url: string;
            /**
             * Land Tiles Url
             * @default
             */
            land_tiles_url: string;
            /**
             * Fire Tiles Url
             * @default
             */
            fire_tiles_url: string;
        };
        /**
         * CoverageRegionResponse
         * @description One configured coverage region with its latest observation ingest (``GET /api/coverage``).
         */
        CoverageRegionResponse: {
            /** Name */
            name: string;
            /** Place Id */
            place_id: number;
            /** Last Ingest */
            last_ingest: string | null;
            /** Observations Ingested */
            observations_ingested: number;
        };
        /**
         * DataHealthResponse
         * @description ``/healthz/data``: overall health plus each layer's freshness.
         */
        DataHealthResponse: {
            /** Ok */
            ok: boolean;
            /** Layers */
            layers: components["schemas"]["LayerFreshnessResponse"][];
        };
        /**
         * FireNear
         * @description An active wildfire or recent burn scar near a point (issue #227) - the card / plan-stop
         *     warning annotation. The map layer moved to vector tiles (issue #336 PR 2), so this no longer
         *     carries geometry.
         */
        FireNear: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Fire Year */
            fire_year: number | null;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Distance Km */
            distance_km: number;
            /** Percent Contained */
            percent_contained: number | null;
            /** Gis Acres */
            gis_acres: number | null;
            /** Dominant Severity */
            dominant_severity: string | null;
            /** Is Point */
            is_point: boolean;
            /** Incident Url */
            incident_url: string | null;
        };
        /**
         * GenusResult
         * @description A genus catalog search hit (issue #79).
         *
         *     ``common_name`` is optional - most of the ~6,018 Fungi genera lack an English common name
         *     on iNat, so ``name`` (scientific) is the primary label, not a fallback.
         */
        GenusResult: {
            /** Taxon Id */
            taxon_id: number;
            /** Name */
            name: string;
            /** Common Name */
            common_name: string | null;
            /**
             * Icon
             * @default generic
             * @enum {string}
             */
            icon: "gilled" | "bolete" | "bracket" | "crust" | "coral" | "puffball" | "earthstar" | "cup" | "morel" | "tooth" | "vase" | "jelly" | "stinkhorn" | "leafy-lichen" | "shrubby-lichen" | "rust" | "generic" | "trametes" | "amanita" | "laetiporus" | "pleurotus" | "fomitopsis" | "cerioporus" | "ganoderma" | "lactarius" | "stereum" | "schizophyllum" | "mycena" | "suillus" | "cladonia" | "omphalotus" | "coprinus" | "flavoparmelia" | "cantharellus" | "hericium" | "desarmillaria" | "lobaria" | "hypomyces" | "chlorophyllum" | "russula" | "cortinarius" | "artomyces" | "apioperdon" | "entoloma" | "agaricus" | "leucocoprinus" | "morchella";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Home
         * @description A home location: display name, coordinates and search radius.
         */
        Home: {
            /**
             * Name
             * @default Home
             */
            name: string;
            /**
             * Lat
             * @default 47.6062
             */
            lat: number;
            /**
             * Lng
             * @default -122.3321
             */
            lng: number;
            /**
             * Radius Km
             * @default 150
             */
            radius_km: number;
        };
        /**
         * LandParcel
         * @description A public-land parcel near a point (``GET /api/land``, issue #311) - ownership only.
         */
        LandParcel: {
            /** Id */
            id: string;
            /** Agency */
            agency: string | null;
            /** Unit */
            unit: string | null;
            /** Url */
            url: string | null;
            /** Distance Km */
            distance_km: number;
        };
        /**
         * LayerFreshnessResponse
         * @description One data layer's freshness, as reported by ``/healthz/data`` (issue #332).
         */
        LayerFreshnessResponse: {
            /** Layer */
            layer: string;
            /** Last Success */
            last_success: string | null;
            /** Interval Hours */
            interval_hours: number;
            /** Stale */
            stale: boolean;
            /** Blocking */
            blocking: boolean;
        };
        /**
         * LocationBody
         * @description Request body for ``POST /api/location``: either ``query`` (a place name) or both ``lat`` and ``lng``, plus an
         *     optional display ``name`` and ``radius_km``.
         */
        LocationBody: {
            /** Query */
            query?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /** Name */
            name?: string | null;
            /** Radius Km */
            radius_km?: number | null;
        };
        /**
         * LocationResponse
         * @description A visitor's saved home, returned by ``POST /api/location``.
         */
        LocationResponse: {
            home: components["schemas"]["Home"];
        };
        /**
         * ObservationPhoto
         * @description A displayable Creative Commons photo with its licence code and the photographer's attribution.
         */
        ObservationPhoto: {
            /** Url */
            url: string;
            /** License Code */
            license_code: string;
            /** Attribution */
            attribution: string;
        };
        /**
         * ObservationThumbnail
         * @description One CC-licensed iNat photo for a precise observation's map popup (issue #449).
         */
        ObservationThumbnail: {
            /** Url */
            url: string;
            /** Attribution */
            attribution: string;
            /** License Code */
            license_code: string;
        };
        /**
         * ObservationThumbnailRequest
         * @description Observation ids whose popup photos the client wants warmed (issue #449).
         */
        ObservationThumbnailRequest: {
            /** Ids */
            ids: number[];
        };
        /**
         * ObservationThumbnails
         * @description Thumbnails by observation id (as a string key). A null value means iNat has no photo we may
         *     display; an id that is absent was not resolved (not a cached precise observation, or the
         *     lookup failed) and falls back to the per-pin endpoint.
         */
        ObservationThumbnails: {
            /** Thumbnails */
            thumbnails: {
                [key: string]: components["schemas"]["ObservationThumbnail"] | null;
            };
        };
        /**
         * PlaceSuggestion
         * @description One typeahead hit from ``/api/location/search`` (issue #145).
         */
        PlaceSuggestion: {
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /**
         * PreciseObservation
         * @description A verified-location (not obscured) observation drawn as a map pin.
         */
        PreciseObservation: {
            /** Id */
            id: number;
            /** Taxon Id */
            taxon_id: number;
            /** Name */
            name: string;
            /** Common Name */
            common_name: string | null;
            /**
             * Icon
             * @default generic
             * @enum {string}
             */
            icon: "gilled" | "bolete" | "bracket" | "crust" | "coral" | "puffball" | "earthstar" | "cup" | "morel" | "tooth" | "vase" | "jelly" | "stinkhorn" | "leafy-lichen" | "shrubby-lichen" | "rust" | "generic" | "trametes" | "amanita" | "laetiporus" | "pleurotus" | "fomitopsis" | "cerioporus" | "ganoderma" | "lactarius" | "stereum" | "schizophyllum" | "mycena" | "suillus" | "cladonia" | "omphalotus" | "coprinus" | "flavoparmelia" | "cantharellus" | "hericium" | "desarmillaria" | "lobaria" | "hypomyces" | "chlorophyllum" | "russula" | "cortinarius" | "artomyces" | "apioperdon" | "entoloma" | "agaricus" | "leucocoprinus" | "morchella";
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Observed On */
            observed_on: string | null;
            /** Uri */
            uri: string | null;
            /** Taxon Name */
            taxon_name?: string | null;
            /** Taxon Common Name */
            taxon_common_name?: string | null;
        };
        /**
         * RecentObservation
         * @description A recent observation in a region's Photos tab, with its displayable photos.
         */
        RecentObservation: {
            /** Id */
            id: number;
            /** Taxon Id */
            taxon_id: number;
            /** Name */
            name: string;
            /** Common Name */
            common_name: string | null;
            /**
             * Icon
             * @default generic
             * @enum {string}
             */
            icon: "gilled" | "bolete" | "bracket" | "crust" | "coral" | "puffball" | "earthstar" | "cup" | "morel" | "tooth" | "vase" | "jelly" | "stinkhorn" | "leafy-lichen" | "shrubby-lichen" | "rust" | "generic" | "trametes" | "amanita" | "laetiporus" | "pleurotus" | "fomitopsis" | "cerioporus" | "ganoderma" | "lactarius" | "stereum" | "schizophyllum" | "mycena" | "suillus" | "cladonia" | "omphalotus" | "coprinus" | "flavoparmelia" | "cantharellus" | "hericium" | "desarmillaria" | "lobaria" | "hypomyces" | "chlorophyllum" | "russula" | "cortinarius" | "artomyces" | "apioperdon" | "entoloma" | "agaricus" | "leucocoprinus" | "morchella";
            /** Observed On */
            observed_on: string | null;
            /** Place Guess */
            place_guess: string | null;
            /** Uri */
            uri: string | null;
            /** Obscured */
            obscured: boolean;
            /** Photos */
            photos: components["schemas"]["ObservationPhoto"][];
        };
        /**
         * RecentObservationsPage
         * @description One page of ``RecentObservation`` rows plus whether a further page exists.
         */
        RecentObservationsPage: {
            /** Observations */
            observations: components["schemas"]["RecentObservation"][];
            /** Has More */
            has_more: boolean;
        };
        /**
         * RegionPlace
         * @description A destination card's titling place name (issue #206), or ``None`` when the region has
         *     no notable place nearby.
         */
        RegionPlace: {
            /** Place Name */
            place_name: string | null;
        };
        /**
         * RegionScore
         * @description One ranked destination: its H3 region, score, contributing genera and the context shown on its card (rain,
         *     elevation, fire, access).
         */
        RegionScore: {
            /** Region Id */
            region_id: string;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Distance Km */
            distance_km: number;
            /** Score */
            score: number;
            /** Score Norm */
            score_norm: number;
            /** N Species */
            n_species: number;
            /** Recent Count */
            recent_count: number;
            /** Species */
            species: components["schemas"]["SpeciesHit"][];
            /** Elevation M */
            elevation_m?: number | null;
            /** Pheno Trend */
            pheno_trend?: string | null;
            /** Precip Obs 7D Mm */
            precip_obs_7d_mm?: number | null;
            /** Precip Obs 30D Mm */
            precip_obs_30d_mm?: number | null;
            /** Precip Recent 7D Mm */
            precip_recent_7d_mm?: number | null;
            /** Precip Recent 14D Mm */
            precip_recent_14d_mm?: number | null;
            /** Precip Recent 30D Mm */
            precip_recent_30d_mm?: number | null;
            /**
             * Fire Nearby
             * @default []
             */
            fire_nearby: components["schemas"]["FireNear"][];
            /** Trailhead Km */
            trailhead_km?: number | null;
            /** Camp Km */
            camp_km?: number | null;
            /** Camp Is Free */
            camp_is_free?: boolean | null;
        };
        /**
         * SpeciesHit
         * @description A target-genus contribution to a ranked region.
         *
         *     ``name`` (scientific) is the primary display label; ``common_name`` is optional
         *     secondary enrichment - most of the ~6,018-genus catalog lacks an English common name.
         */
        SpeciesHit: {
            /** Taxon Id */
            taxon_id: number;
            /** Name */
            name: string;
            /** Common Name */
            common_name: string | null;
            /** Month Count */
            month_count: number;
            /** Total Count */
            total_count: number;
            /** W Pheno */
            w_pheno: number;
            /**
             * Icon
             * @default generic
             * @enum {string}
             */
            icon: "gilled" | "bolete" | "bracket" | "crust" | "coral" | "puffball" | "earthstar" | "cup" | "morel" | "tooth" | "vase" | "jelly" | "stinkhorn" | "leafy-lichen" | "shrubby-lichen" | "rust" | "generic" | "trametes" | "amanita" | "laetiporus" | "pleurotus" | "fomitopsis" | "cerioporus" | "ganoderma" | "lactarius" | "stereum" | "schizophyllum" | "mycena" | "suillus" | "cladonia" | "omphalotus" | "coprinus" | "flavoparmelia" | "cantharellus" | "hericium" | "desarmillaria" | "lobaria" | "hypomyces" | "chlorophyllum" | "russula" | "cortinarius" | "artomyces" | "apioperdon" | "entoloma" | "agaricus" | "leucocoprinus" | "morchella";
        };
        /**
         * StatusResponse
         * @description A one-word outcome (``ok``, ``started``, ``added``, ``deleted``, ...) for routes with nothing else to return.
         */
        StatusResponse: {
            /** Status */
            status: string;
        };
        /**
         * Stop
         * @description One planned stop: its region, distances along the route, the nearby camp and trail, fire warnings and any pin.
         */
        Stop: {
            /** Order */
            order: number;
            /** Region Id */
            region_id: string;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Score Norm */
            score_norm: number;
            /** N Species */
            n_species: number;
            /** Recent Count */
            recent_count: number;
            /** Species */
            species: components["schemas"]["SpeciesHit"][];
            /** Progress Km */
            progress_km: number;
            /** Drive Km From Prev */
            drive_km_from_prev: number;
            /** Cumulative Drive Km */
            cumulative_drive_km: number;
            camp: components["schemas"]["CampSite"] | null;
            /** Camp Is Free */
            camp_is_free: boolean;
            trail: components["schemas"]["Trail"] | null;
            /** Trail Distance Km */
            trail_distance_km: number | null;
            /**
             * Fire Nearby
             * @default []
             */
            fire_nearby: components["schemas"]["FireNear"][];
            pin?: components["schemas"]["StopPin"] | null;
        };
        /**
         * StopPin
         * @description A campground, trail or public-land parcel the user pinned as a trip stop's exact point.
         */
        StopPin: {
            /** Kind */
            kind: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Feature Kind */
            feature_kind: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /**
         * Trail
         * @description A trailhead, path, forest road or hiking route near a point, with its distance, length, land owner and foraging
         *     hint.
         */
        Trail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Distance Km */
            distance_km: number;
            /** Camp Distance Km */
            camp_distance_km: number | null;
            /** Length Km */
            length_km?: number | null;
            /** Attrs */
            attrs?: {
                [key: string]: string;
            } | null;
            /**
             * Walk In
             * @default false
             */
            walk_in: boolean;
            /** Land Agency */
            land_agency?: string | null;
            /** Land Unit */
            land_unit?: string | null;
            /** Forage Obs */
            forage_obs?: number | null;
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TrailPath
         * @description The full geometry of one trail (``GET /api/trails/network``) and whether it is authoritative (real OSM topology)
         *     or the nearest cached fallback.
         */
        TrailPath: {
            trail: components["schemas"]["Trail"];
            /** Authoritative */
            authoritative: boolean;
        };
        /**
         * TripPlan
         * @description A planned trip (``GET /api/plan``): start, destination, ordered stops and totals. Distances are straight-line.
         */
        TripPlan: {
            /** Start Lat */
            start_lat: number;
            /** Start Lng */
            start_lng: number;
            /** Destination Lat */
            destination_lat: number;
            /** Destination Lng */
            destination_lng: number;
            /** Destination Name */
            destination_name: string | null;
            /** Auto Destination */
            auto_destination: boolean;
            /** Corridor Km */
            corridor_km: number;
            /** Months */
            months: number[];
            /** N Stops */
            n_stops: number;
            /** Total Drive Km */
            total_drive_km: number;
            /** Stops */
            stops: components["schemas"]["Stop"][];
            /** Skipped Unreachable */
            skipped_unreachable: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    get_genera_api_genera_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenusResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_selected_genera_api_genera_selected_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenusResult"][];
                };
            };
        };
    };
    add_selected_genus_api_genera__taxon_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_selected_genus_api_genera__taxon_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coverage_api_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageRegionResponse"][];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    healthz_data_healthz_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataHealthResponse"];
                };
            };
            /** @description At least one layer's latest success is older than its expected interval. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataHealthResponse"];
                };
            };
        };
    };
    healthz_backlog_healthz_backlog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacklogResponse"][];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain; version=1.0.0; charset=utf-8": unknown;
                };
            };
        };
    };
    destinations_api_destinations_get: {
        parameters: {
            query?: {
                months?: string | null;
                species?: string;
                radius_km?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionScore"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calendar_api_calendar_get: {
        parameters: {
            query: {
                region_id: string;
                species?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["CalendarBucket"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observation_photos_api_observations_photos_get: {
        parameters: {
            query: {
                region_id: string;
                species?: string;
                months?: string | null;
                weeks?: number | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentObservationsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alerts_api_alerts_get: {
        parameters: {
            query?: {
                species?: string;
                weeks?: number | null;
                radius_km?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRegion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observations_precise_api_observations_precise_get: {
        parameters: {
            query?: {
                species?: string;
                months?: string | null;
                weeks?: number | null;
                lat?: number | null;
                lng?: number | null;
                radius_km?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreciseObservation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observation_thumbnail_api_observations__obs_id__thumbnail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obs_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationThumbnail"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observation_thumbnails_api_observations_thumbnails_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationThumbnailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationThumbnails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camps_api_camps_get: {
        parameters: {
            query?: {
                region_id?: string | null;
                lat?: number | null;
                lng?: number | null;
                radius_km?: number;
                free_only?: boolean;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampSite"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_region_places_api_destinations_places_get: {
        parameters: {
            query: {
                /** @description comma-separated region ids */
                region_ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["RegionPlace"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_region_place_api_destinations__region_id__place_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                region_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionPlace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_region_satellite_image_api_destinations__region_id__satellite_image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                region_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_region_satellite_labels_api_destinations__region_id__satellite_labels_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                region_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_land_api_land_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                radius_km?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandParcel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trails_api_trails_get: {
        parameters: {
            query?: {
                region_id?: string | null;
                lat?: number | null;
                lng?: number | null;
                radius_km?: number;
                kind?: string | null;
                limit?: number | null;
                sort?: "nearest" | "relevance" | "longest";
                significant_only?: boolean;
                distinct_names?: boolean;
                species?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trail_network_api_trails_network_get: {
        parameters: {
            query: {
                trail_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrailPath"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_satellite_tile_api_tiles_satellite__z___x___y__jpg_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trails_tile_api_tiles_trails__z___x___y__pbf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.mapbox-vector-tile": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_land_tile_api_tiles_land__z___x___y__pbf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.mapbox-vector-tile": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fire_tile_api_tiles_fire__z___x___y__pbf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.mapbox-vector-tile": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_plan_get: {
        parameters: {
            query?: {
                months?: string | null;
                species?: string;
                start?: string | null;
                destination?: string | null;
                corridor_km?: number;
                max_stops?: number;
                max_drive_km?: number;
                camp_radius_km?: number;
                require_free_camp?: boolean;
                waypoints?: string | null;
                pin?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_location_api_location_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_location_api_location_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    search_location_api_location_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceSuggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_refresh_post: {
        parameters: {
            query?: {
                target?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_refresh_api_refresh_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    refresh_stream_api_refresh_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent progress events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
