---
- name: Create managed Postgres cluster
  digitalocean.cloud.database_cluster:
    token: "{{ foray_do_token }}"
    state: present
    name: "{{ foray_do_db_cluster_name }}"
    engine: "{{ foray_do_db_engine }}"
    version: "{{ foray_do_db_version }}"
    size: "{{ foray_do_db_size }}"
    region: "{{ foray_do_region }}"
    num_nodes: 1
  register: foray_db_cluster

- name: Create application database within the cluster
  digitalocean.cloud.database_db:
    token: "{{ foray_do_token }}"
    state: present
    cluster_id: "{{ foray_db_cluster.database.id }}"
    name: "{{ foray_do_db_name }}"

- name: Store database connection info
  ansible.builtin.set_fact:
    foray_db_host: "{{ foray_db_cluster.database.connection.host }}"
    foray_db_port: "{{ foray_db_cluster.database.connection.port }}"
    foray_db_user: "{{ foray_db_cluster.database.connection.user }}"
    foray_db_password: "{{ foray_db_cluster.database.connection.password }}"
