---
- name: Provision Digital Ocean infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - defaults/main.yml
  tasks:
    - name: Include database provisioning
      ansible.builtin.include_tasks:
        file: tasks/provision/database.yml
        apply:
          tags:
            - foray
            - "foray:provision"
            - "foray:deploy"
      tags:
        - foray
        - "foray:provision"
        - "foray:deploy"

    - name: Include droplet provisioning
      ansible.builtin.include_tasks:
        file: tasks/provision/droplet.yml
        apply:
          tags:
            - foray
            - "foray:provision"
      tags:
        - foray
        - "foray:provision"

    - name: Include firewall provisioning
      ansible.builtin.include_tasks:
        file: tasks/provision/firewall.yml
        apply:
          tags:
            - foray
            - "foray:provision"
      tags:
        - foray
        - "foray:provision"

    - name: Include droplet resize
      ansible.builtin.include_tasks:
        file: tasks/provision/droplet_resize.yml
        apply:
          tags:
            - "foray:resize"
            - never
      tags:
        - "foray:resize"
        - never

- name: Deploy foray-planner
  hosts: foray
  gather_facts: false
  vars_files:
    - defaults/main.yml
  tasks:
    - name: Create app directory
      ansible.builtin.file:
        path: /opt/foray-planner
        state: directory
        mode: "0700"
      tags:
        - foray
        - "foray:deploy"
        - "foray:cron"

    - name: Include docker network tasks
      ansible.builtin.include_tasks:
        file: tasks/deploy/network.yml
        apply:
          tags:
            - foray
            - "foray:deploy"
      tags:
        - foray
        - "foray:deploy"

    - name: Include deploy tasks
      ansible.builtin.include_tasks:
        file: tasks/deploy/app.yml
        apply:
          tags:
            - foray
            - "foray:deploy"
      tags:
        - foray
        - "foray:deploy"

    - name: Include caddy (TLS reverse proxy) tasks
      ansible.builtin.include_tasks:
        file: tasks/deploy/caddy.yml
        apply:
          tags:
            - foray
            - "foray:deploy"
      tags:
        - foray
        - "foray:deploy"

    - name: Include cron tasks
      ansible.builtin.include_tasks:
        file: tasks/deploy/cron.yml
        apply:
          tags:
            - foray
            - "foray:cron"
      tags:
        - foray
        - "foray:cron"

    - name: Include one-off ingest task
      ansible.builtin.include_tasks:
        file: tasks/deploy/ingest_once.yml
        apply:
          tags:
            - "foray:ingest-once"
            - never
      tags:
        - "foray:ingest-once"
        - never

  handlers:
    - name: Include handlers
      ansible.builtin.import_tasks:
        file: handlers/main.yml
