"""Built-in default species and coverage region lists."""

from __future__ import annotations

SPECIES = [
    {"taxon_id": 47348, "name": "Cantharellus", "common_name": "Chanterelles", "rank": "genus"},
    {"taxon_id": 48611, "name": "Craterellus", "common_name": "Black Trumpets", "rank": "genus"},
    {"taxon_id": 56830, "name": "Morchella", "common_name": "Morels", "rank": "genus"},
    {
        "taxon_id": 48703,
        "name": "Boletus",
        "common_name": "King Boletes & Porcini",
        "rank": "genus",
    },
    {"taxon_id": 53490, "name": "Suillus", "common_name": "Slippery Jacks", "rank": "genus"},
    {"taxon_id": 54203, "name": "Leccinum", "common_name": "Scaber Stalks", "rank": "genus"},
    {"taxon_id": 48422, "name": "Hydnum", "common_name": "Hedgehogs", "rank": "genus"},
    {"taxon_id": 49160, "name": "Hericium", "common_name": "Lion's Mane", "rank": "genus"},
    {
        "taxon_id": 48431,
        "name": "Laetiporus",
        "common_name": "Chicken of the Woods",
        "rank": "genus",
    },
    {"taxon_id": 53716, "name": "Grifola", "common_name": "Hen of the Woods", "rank": "genus"},
    {
        "taxon_id": 63020,
        "name": "Sparassis",
        "common_name": "Cauliflower Mushrooms",
        "rank": "genus",
    },
    {"taxon_id": 48496, "name": "Pleurotus", "common_name": "Oyster Mushrooms", "rank": "genus"},
    {
        "taxon_id": 62484,
        "name": "Tricholoma",
        "common_name": "Matsutake & Tricholomas",
        "rank": "genus",
    },
    {"taxon_id": 55591, "name": "Lepista", "common_name": "Blewits", "rank": "genus"},
    {"taxon_id": 54597, "name": "Lactarius", "common_name": "Milk Caps", "rank": "genus"},
    {
        "taxon_id": 49548,
        "name": "Agaricus",
        "common_name": "Field & Button Mushrooms",
        "rank": "genus",
    },
    {"taxon_id": 47393, "name": "Coprinus", "common_name": "Shaggy Manes", "rank": "genus"},
    {"taxon_id": 57693, "name": "Calvatia", "common_name": "Giant Puffballs", "rank": "genus"},
    {"taxon_id": 48444, "name": "Lycoperdon", "common_name": "Puffballs", "rank": "genus"},
    {"taxon_id": 48246, "name": "Hypomyces", "common_name": "Lobster Mushroom", "rank": "genus"},
    {"taxon_id": 50817, "name": "Auricularia", "common_name": "Wood Ears", "rank": "genus"},
]

COVERAGE = [
    {"name": "Washington", "place_id": 46},
    {"name": "Oregon", "place_id": 10},
    {"name": "Idaho", "place_id": 22},
]

ALL_STATES = [
    {"name": "Alabama", "place_id": 19},
    {"name": "Alaska", "place_id": 6},
    {"name": "Arizona", "place_id": 40},
    {"name": "Arkansas", "place_id": 36},
    {"name": "California", "place_id": 14},
    {"name": "Colorado", "place_id": 34},
    {"name": "Connecticut", "place_id": 49},
    {"name": "Delaware", "place_id": 4},
    {"name": "Florida", "place_id": 21},
    {"name": "Georgia", "place_id": 23},
    {"name": "Hawaii", "place_id": 11},
    {"name": "Idaho", "place_id": 22},
    {"name": "Illinois", "place_id": 35},
    {"name": "Indiana", "place_id": 20},
    {"name": "Iowa", "place_id": 24},
    {"name": "Kansas", "place_id": 25},
    {"name": "Kentucky", "place_id": 26},
    {"name": "Louisiana", "place_id": 27},
    {"name": "Maine", "place_id": 17},
    {"name": "Maryland", "place_id": 39},
    {"name": "Massachusetts", "place_id": 2},
    {"name": "Michigan", "place_id": 29},
    {"name": "Minnesota", "place_id": 38},
    {"name": "Mississippi", "place_id": 37},
    {"name": "Missouri", "place_id": 28},
    {"name": "Montana", "place_id": 16},
    {"name": "Nebraska", "place_id": 3},
    {"name": "Nevada", "place_id": 50},
    {"name": "New Hampshire", "place_id": 41},
    {"name": "New Jersey", "place_id": 51},
    {"name": "New Mexico", "place_id": 9},
    {"name": "New York", "place_id": 48},
    {"name": "North Carolina", "place_id": 30},
    {"name": "North Dakota", "place_id": 13},
    {"name": "Ohio", "place_id": 31},
    {"name": "Oklahoma", "place_id": 12},
    {"name": "Oregon", "place_id": 10},
    {"name": "Pennsylvania", "place_id": 42},
    {"name": "Rhode Island", "place_id": 8},
    {"name": "South Carolina", "place_id": 43},
    {"name": "South Dakota", "place_id": 44},
    {"name": "Tennessee", "place_id": 45},
    {"name": "Texas", "place_id": 18},
    {"name": "Utah", "place_id": 52},
    {"name": "Vermont", "place_id": 47},
    {"name": "Virginia", "place_id": 7},
    {"name": "Washington", "place_id": 46},
    {"name": "West Virginia", "place_id": 33},
    {"name": "Wisconsin", "place_id": 32},
    {"name": "Wyoming", "place_id": 15},
]
